# .github/workflows/android-build.yml

name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_API_LEVEL: 27
      ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
      ANDROID_NDK_VERSION: "23b"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython

      - name: Set up Android SDK
        uses: malinskiy/action-android@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}
          ndk: ${{ env.ANDROID_NDK_VERSION }}

      - name: Accept Android SDK licenses
        run: |
          yes | "$ANDROID_HOME/tools/bin/sdkmanager" --licenses

      - name: Build APK
        run: |
          buildozer android debug
