# .github/workflows/android-build.yml

name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_API_LEVEL: 27
      ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
      ANDROID_NDK_PACKAGE: "ndk;25.2.9519653"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            pkg-config \
            gperf \
            m4 \
            autoconf-archive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython

      - name: Install Android SDK tools
        uses: malinskiy/action-android/install-sdk@release/0.1.7

      - name: Create legacy tools/bin SDKManager shim
        run: |
          mkdir -p $ANDROID_SDK_ROOT/tools/bin
          ln -sf $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager $ANDROID_SDK_ROOT/tools/bin/sdkmanager

      - name: Install Android platforms, build-tools & NDK
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-${{ env.ANDROID_API_LEVEL }}" \
                     "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}" \
                     "${{ env.ANDROID_NDK_PACKAGE }}"

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer -v android debug
